Mission07/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission07.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission07.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        
        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Mission07/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission07.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission07.Components
{
    public class CategoryViewComponent : ViewComponent
    { 
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"]; //it's okay if null (?)

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Mission07/Views/Shared/BookSummary.cshtml
@{

}

@model Book

<div class="card" card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            @Model.Isbn
        </span>
    </div>

    <ul>
        <li>Author: @Model.Author.</li>
        <li>Publisher: @Model.Publisher</li>
        <li>Classification: @Model.Classification</li>
        <li>ISBN: @Model.Category</li>
        <li>PageCount: @Model.PageCount</li>
        <li>Price: @Model.Price</li>
    </ul>

    @*When button is clicked, go to Cart page*@
    <form method="post" asp-page="/Cart">
       @*It is referencing a specific bookid, but we don't want to see it*@
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

Mission07/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Online Bookstore</title>
    @*MISSION 10 - FAVICON ADDED*@
    <link rel="shortcut icon" type="image/svg" href="~/lib/img/book.svg"/>
     <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand" m-lg-2> My Online Bookstore</span>
        @*(in mission10, go on to float right)*@
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand">SPORTS STORE</div>
                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row m-1 p-1">

        <div id="category" class="col-3">
            <vc:category></vc:category>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>


</body>
</html>